server:
  port: 8080
  servlet:
    context-path: /openAdmin

spring:
  profiles:
    active: dev
  application:
    name: open-admin
  main:
    allow-bean-definition-overriding: true # SpringBoot 2.1需要设置

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-enums-package: com.saucesubfresh.admin.server.enums*;com.saucesubfresh.admin.common.enums*
  global-config:
    db-config:
      id-type: auto

